add function to handle accounts with digits
Xerpa/bank_validator_br pull request #14
Opened 2020-09-10 19:04 UTC by raphaeltelatim

Adicionada assinatura para função `BankValidatorBR.is_valid?/3" para receber contas com dígito.

2020-09-10 19:12 UTC, brunorafa commented on lib/bank_validator_br.ex
> +    raise ArgumentError, message: "Invalid account number format"
Acho que ficaria melhor nao usar o raise aqui, quando eu uso uma `func?` eu espero que ela seja "safe" e nao exploda.

2020-09-10 19:14 UTC, raphaeltelatim commented on lib/bank_validator_br.ex
> +    raise ArgumentError, message: "Invalid account number format"
@brunorafa Faz sentido, vamos retornar então só o boolean `false`. Creio que mais pra frente vamos retornar uma `tuple` com a descrição do erro.

2020-09-10 19:15 UTC, brunorafa commented on lib/bank_validator_br.ex
> +    raise ArgumentError, message: "Invalid account number format"
assim como seu @spec "promete" que ela sempre vai retornar um `Boolean.t()`

2020-09-10 19:21 UTC, alansousa commented on lib/bank_validator_br.ex
> +      |> String.split_at(-1)
poderia usar apenas o `String.split/2`
```elixir
iex(2)> "123123-3" |> String.split("-")
["123123", "3"]
```

2020-09-10 19:21 UTC, alansousa commented on lib/bank_validator_br.ex
> +    end
porque nao evitamos o raise aqui?
Validamos se existe alguma regra de digito com letra?

2020-09-10 19:21 UTC, alansousa commented on lib/bank_validator_br.ex
> +  def is_valid?(bank_code, agency_code, account_number, digit) when is_integer(digit) do
porque esperamos que todos sejam string, mas o digito tenha que ser convertido pra int antes?

2020-09-10 19:28 UTC, raphaeltelatim commented on lib/bank_validator_br.ex
> +      |> String.split_at(-1)
@alan Do jeito que eu deixei podemos receber a conta com ou sem o hífen

2020-09-10 19:29 UTC, raphaeltelatim commented on lib/bank_validator_br.ex
> +    end
Na teoria não receberemos letras mesmo, vou tirar

2020-09-10 19:33 UTC, raphaeltelatim commented on lib/bank_validator_br.ex
> +  def is_valid?(bank_code, agency_code, account_number, digit) when is_integer(digit) do
@alan O dígito é uma das maneiras de verificar se a conta é válida, por exemplo no caso do Santander são feitos alguns cálculos com os números da conta e ai verifica-se se o valor obtido é igual ao dígito. Poderíamos recebê-lo como string também e ai fazer a conversão dentro das funções que fazem o cálculo também, sei lá...

2020-09-10 21:53 UTC, itsmegrave commented on lib/bank_validator_br.ex
> +  def is_valid?(bank_code, agency_code, account_number, digit) when is_integer(digit) do
o digito pode ser string, como rola no Bradesco por exemplo.

2020-09-10 22:03 UTC, itsmegrave requested changes

2020-09-10 22:03 UTC, itsmegrave commented on lib/bank_validator_br.ex
> +    end
acho que não precisamos dessa validação do digito ser um numero.
Pq temos bradesco e BB com digito como string ("P" e "X").
faz sentido mudar a função antiga, `is_valid?/4` pra não considerar o digiito como numero

2020-09-14 12:08 UTC, alansousa approved these changes

2020-09-14 14:11 UTC, itsmegrave requested changes

2020-09-14 14:11 UTC, itsmegrave commented on lib/bank_validator_br.ex
> +  def is_valid?(bank_code, agency_code, account_number, digit) when is_integer(digit) do
não precisamos desse guard pro digito :) 
pode entrar uma string aqui também

2020-09-14 14:11 UTC, itsmegrave commented on lib/bank_validator_br.ex
> +    {parsed_digit, _} = Integer.parse(digit)
não vamos precisar desse parse aqui, o digito pode ser uma letra

2020-09-14 16:40 UTC, itsmegrave commented
@raphaeltelatim linkei a issue ao seu pr :)

2020-09-14 17:59 UTC, itsmegrave approved these changes

2020-09-14 18:26 UTC, merged